---
name: build

on:
  push:
    branches: [ master ]
  create:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "Hello"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Build & Test
        run: make
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: './gen/dist/*'
