---
name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Build & Test
        run: make
      

---
name: release

on: 
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './gen/dist/*'
          draft: true      
