name: release

on: 
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './gen/dist/*'
          draft: true      
